matrix:
  include:
    - os: linux
      language: c
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      language: objective-c

branches:
  only:
    - master

compiler:
  - gcc

env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - .travis/install_ssh_id.sh
  - unset SSH_ID
  - .travis/install_prerequisities.sh

before_script:
  - . ./.travis/setup_env.sh

script:
  - . ./.travis/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
