language: c
os: linux
dist: trusty
sudo: required

branches:
  only:
  - master

compiler:
  - gcc

addons:
  apt:
    packages:
    - curl
    - libosmesa6-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libusb-dev
    - libusb-1.0-0-dev

before_install:
  - .travis/install_ssh_id.sh
  - unset SSH_ID

before_script:
  - . ./.travis/setup_env.sh

script:
  - . ./.travis/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
